# Generated by Django 5.1.3 on 2024-12-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(max_length=100)),
                ('banner_image_1', models.ImageField(upload_to='banner_images/')),
                ('banner_image_2', models.ImageField(upload_to='banner_images/')),
                ('banner_image_3', models.ImageField(upload_to='banner_images/')),
                ('banner_image_4', models.ImageField(upload_to='banner_images/')),
                ('banner_image_5', models.ImageField(upload_to='banner_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
