# Generated by Django 5.1.3 on 2024-12-30 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_websetting_delete_banner_delete_webname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebName',
            fields=[
                ('web_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='websetting',
            name='web_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='administrator.webname'),
        ),
    ]
