# Generated by Django 5.1.3 on 2024-12-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_webname_alter_websetting_web_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebSetting',
            new_name='Banner',
        ),
    ]
