# Generated by Django 5.1.3 on 2024-12-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_websetting_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebName',
            new_name='WebSetting',
        ),
    ]
